## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

cloud:
  # supported: amazon, azure, google
  provider:
  # zones:
  #   - us-east-2a
  #   - us-east-2b
  #   - us-east-2c

nuodb:
  image:
    registry: docker.io
    repository: nuodb/nuodb-ce
    tag: 4.0.2
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
    ##
    # pullSecrets:
    # - myRegistryKeySecretName
    ## Specify a imagePullPolicy
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##

# Admin info
admin:
  # nameOverride: east
  # fullnameOverride: admin-east
  # namespace: nuodb
  domain: nuodb
  # tlsCACert:
  #   secret: nuodb-ca-cert
  #   key: ca.cert
  # tlsClientPEM:
  #   secret: nuodb-client-pem
  #   key: client.pem

database:
  # dbName
  # NuoDB Database name.  must consist of lowercase alphanumeric
  #characters '[a-z0-9]+'
  name: demo

backup:
  ## Schedule for the running the full backup cron job
  ## 
  ## At 22:35 on every day-of-month if it's on Sunday
  fullSchedule: 35 22 */1 * 6

  ## Schedule for the running the incremental backup cron job
  ##
  ## At 22:35 on every day-of-month if it's on every day-of-week from Monday through Saturday
  incrementalSchedule: 35 22 */1 * 0-5

  ## Deadline for scheduling the job
  deadline: 1800

  ## Success history for the job
  successHistory: 5

  ## Failure history for the job
  failureHistory: 3

  timeout: 1800

  backupDir: /var/opt/nuodb/backup

  coldStorage:
    credentials: ""

