{{/*

 This job is used to create the hotcopy backup volume PVCs based upon
 a snapshot handle.

*/}}
{{- if .Values.backupmgr.restore.source }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: {{ template "database.fullname" . }}
        component: sm
        role: hotcopy
        group: nuodb
        database: {{ .Values.database.name }}
        domain: {{ .Values.admin.domain }}
        chart: {{ template "database.chart" . }}
        release: {{ .Release.Name | quote }}
        use: backup-volume
    spec:
      restartPolicy: Never
      serviceAccountName: "{{ .Values.backupmgr.restore.serviceAccount.name }}"
      containers:
      - name: main
        image: {{ template "aws.sidecar" . }}
        imagePullPolicy: {{ .Values.backupmgr.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - "wait_for_fsr {{ .Values.backupmgr.restore.source }} && create_pvcs {{ .Values.backupmgr.restore.source }} {{ .Values.database.sm.hotCopy.replicas }} backup-volume-sm-{{ template "database.fullname" . }}-hotcopy"
        env:
        - name: LABELSFILE
          value: /etc/pvcinfo/labels
        - name: STORAGECLASS
        {{- if .Values.backupmgr.restore.storageClass }}
        {{- if (eq "-" .Values.backupmgr.restore.storageClass) }}
          value: ""
        {{- else }}
          value: {{ .Values.backupmgr.restore.storageClass }}
        {{- end }}
        {{- else }}
          value: ""     
        {{- end }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: podinfo
          mountPath: /etc/pvcinfo
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
{{- end }}