## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

cloud:
  # supported: amazon, azure, google
  provider:
  # zones:
  #   - us-east-2a
  #   - us-east-2b
  #   - us-east-2c

admin:
  domain: nuodb

database:
  # dbName
  # NuoDB database name.  must consist of lowercase alphanumeric
  #characters '[a-z0-9]+'
  name: demo

ycsb:
  # nameOverride: east
  # fullnameOverride: admin-east

  # replicas
  # Number of YCSB pods
  replicas: 0

  # Use a direct TE connection
  teDirect: false

  # loadName
  # YCSB workload pod name
  loadName: ycsb-load

  # workload
  # YCSB workload.  Valid values are a-f. Each letter determines a different
  # mix of read and update workload percentage generated. a= 50/50, b=95/5,
  # c=100 read. Refer to YCSB documentation for more detail
  workload: b

  # lbPolicy
  # YCSB load-balancer policy. Name of an existing load-balancer policy, that
  # has already been created using the 'nuocmd set load-balancer' command.
  lbPolicy: nearest

  # noOfProcesses
  # Number of YCSB processes. Number of concurrent YCSB processes that will
  # be started in each YCSB pod. Each YCSB process makes a connection to the
  # database.
  noOfProcesses: 2

  # noOfRows: 10000
  # YCSB number of initial rows in table
  noOfRows: 10000

  # noOfIterations
  # YCSB number of iterations
  noOfIterations: 0

  # opsPerIteration
  # Number of YCSB SQL operations to perform in each iteration.
  # This value controls the number of SQL operations performed in each benchmark
  # iteration. Increasing this value increases the run-time of each iteration,
  # and also reduces the frequency at which new connections are made during the
  # sample workload run period.
  opsPerIteration: 10000

  # maxDelay
  # YCSB maximum workload delay in milliseconds (Default is 4 minutes)
  maxDelay: 240000

  # dbSchema
  # YCSB Database schema.  Default schema to use to resolve tables, views, etc
  dbSchema: USER

  # YCSB fully qualified image name (FQIN) for the Docker image to use
  image:
    registry: docker.io
    repository: nuodb/ycsb
    tag: latest
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
    ##
    # pullSecrets:
    # - myRegistryKeySecretName
    ## Specify a imagePullPolicy
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##

  affinity: {}
  # nodeSelector: {}
  # tolerations: []
  
