{{- if and .Values.cloudbeaver.serviceAccount (eq (include "defaulttrue" .Values.cloudbeaver.addServiceAccount) "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cloudbeaver.serviceAccount }}
{{- end }}
