apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "restore.resourceLabels" . | nindent 4 }}
  name: {{ template "restore.fullname" . }}-nuorestore
data:
{{ (.Files.Glob "files/nuorestore").AsConfig | indent 2 }}
