apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "restore.fullname" . }}
  labels:
    {{- include "restore.resourceLabels" . | nindent 4 }}
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: {{ .Values.restore.timeout }}
  template:
    metadata:
      labels:
        {{- include "restore.resourceLabels" . | nindent 8 }}
    spec:
      {{- include "securityContext" . | indent 6 }}
{{- if .Values.restore.affinity }}
      affinity:
{{ tpl .Values.restore.affinity . | trim | indent 8 }}
{{- end }}
      containers:
      - name: restore
        image: {{ template "nuodb.image" . }}
        imagePullPolicy: {{ default "" .Values.nuodb.image.pullPolicy | quote }}

        ##
        # call the nuorestore script
        ##
{{- include "restore.args" . | indent 8 }}
    {{- include "restore.envFrom" . | indent 8 }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "database.secretName" . }}
              key: database-name
        - name: DATABASE_RESTORE_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: {{ template "database.secretName" . }}
              key: database-restore-credentials
        - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888"}
        - { name: NUODB_RESTORE_URL,   value: "{{ include "restore.source" . }}" }
        - { name: NUODB_RESTORE_CREDENTIALS, value: "{{ .Values.restore.credentials }}" }
        - { name: NUODB_RESTORE_REQUEST_STRIP_LEVELS, value: {{ default "1" .Values.restore.stripLevels | quote }} }
        {{- include "sc.containerSecurityContext" . | indent 8 }}
        resources:
        {{- toYaml .Values.restore.resources | trim | nindent 10 }}
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/nuodb
        - name: nuorestore
          mountPath: /usr/local/bin/nuorestore
          subPath: nuorestore
        {{- if .Values.admin.tlsCACert }}
        - name: tls-ca-cert
          mountPath: /etc/nuodb/keys/ca.cert
          subPath: {{ .Values.admin.tlsCACert.key }}
        {{- end }}
        {{- if .Values.admin.tlsClientPEM }}
        - name: tls-client-pem
          mountPath: /etc/nuodb/keys/nuocmd.pem
          subPath: {{ .Values.admin.tlsClientPEM.key }}
        {{- end }}
{{- include "nuodb.imagePullSecrets" . | indent 6 }}
      volumes:
      - name: log-volume
        {{- include "database.ephemeralVolume" . | indent 8 }}
      - name: nuorestore
        configMap:
          name: {{ template "restore.fullname" . }}-nuorestore
          defaultMode: 0777
      {{- if .Values.admin.tlsCACert }}
      - name: tls-ca-cert
        secret:
          secretName: {{ .Values.admin.tlsCACert.secret }}
          defaultMode: 0440
      {{- end }}
      {{- if .Values.admin.tlsClientPEM }}
      - name: tls-client-pem
        secret:
          secretName: {{ .Values.admin.tlsClientPEM.secret }}
          defaultMode: 0440
      {{- end }}
      restartPolicy: Never
