---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: full-backup-{{ .Values.database.name }}-cronjob
  labels:
    group: nuodb
    subgroup: backup
    database: {{ .Values.database.name }}
spec:
  schedule: {{ .Values.backup.fullSchedule}}
  startingDeadlineSeconds: {{ .Values.backup.deadline}}
  successfulJobsHistoryLimit: {{ .Values.backup.successHistory}}
  failedJobsHistoryLimit: {{ .Values.backup.failureHistory}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nuodb
            image: {{ template "nuodb.image" . }}
            imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
            args:
            - "nuobackup"
            - "--type"
            - "full"
            - "--group"
            - {{ include "hotcopy.group" . }}
            - "--timeout"
            - "{{ .Values.backup.timeout }}"      
            - "--backup-root"
            - "{{ .Values.backup.backupDir }}"
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - { name: DB_NAME,             value: "{{ .Values.database.name }}"     }
            - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888" }
            - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
            - { name: TIMEOUT,             value: "{{ .Values.backup.timeout }}" }
            - { name: BACKUP_DIR,          value: "{{ .Values.backup.backupDir }}" }
            volumeMounts:
            {{- if .Values.admin.tlsCACert }}
            - name: tls-ca-cert
              mountPath: /etc/nuodb/keys/ca.cert
              subPath: {{ .Values.admin.tlsCACert.key }}
            {{- end }}
            {{- if .Values.admin.tlsClientPEM }}
            - name: tls-client-pem
              mountPath: /etc/nuodb/keys/nuocmd.pem
              subPath: {{ .Values.admin.tlsClientPEM.key }}
            {{- end }}
          volumes:
          {{- if .Values.admin.tlsCACert }}
          - name: tls-ca-cert
            secret:
              secretName: {{ .Values.admin.tlsCACert.secret }}
              defaultMode: 0440
          {{- end }}
          {{- if .Values.admin.tlsClientPEM }}
          - name: tls-client-pem
            secret:
              secretName: {{ .Values.admin.tlsClientPEM.secret }}
              defaultMode: 0440
          {{- end }}
          restartPolicy: Never
{{- include "nuodb.imagePullSecrets" . | indent 10 }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: incremental-backup-{{ .Values.database.name }}-cronjob
  labels:
    group: nuodb
    subgroup: backup
    database: {{ .Values.database.name }}
spec:
  schedule: {{ .Values.backup.incrementalSchedule}}
  startingDeadlineSeconds: {{ .Values.backup.deadline}}
  successfulJobsHistoryLimit: {{ .Values.backup.successHistory}}
  failedJobsHistoryLimit: {{ .Values.backup.failureHistory}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nuodb
            image: {{ template "nuodb.image" . }}
            imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
            args:
            - "nuobackup"
            - "--type"
            - "incremental"
            - "--labels"
            - "backup {{ .Values.cloud.clusterName }}"
            - "--timeout"
            - "{{ .Values.backup.timeout }}"      
            - "--backup-root"
            - "{{ .Values.backup.backupDir }}"
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - { name: DB_NAME,             value: "{{ .Values.database.name }}"     }
            - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888" }
            - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
            - { name: TIMEOUT,             value: "{{ .Values.backup.timeout }}" }
            - { name: BACKUP_DIR,          value: "{{ .Values.backup.backupDir }}" }
            volumeMounts:
            {{- if .Values.admin.tlsCACert }}
            - name: tls-ca-cert
              mountPath: /etc/nuodb/keys/ca.cert
              subPath: {{ .Values.admin.tlsCACert.key }}
            {{- end }}
            {{- if .Values.admin.tlsClientPEM }}
            - name: tls-client-pem
              mountPath: /etc/nuodb/keys/nuocmd.pem
              subPath: {{ .Values.admin.tlsClientPEM.key }}
            {{- end }}
          volumes:
        - name: nuosm
          mountPath: /usr/local/bin/nuosm
          subPath: nuosm
          {{- if .Values.admin.tlsCACert }}
          - name: tls-ca-cert
            secret:
              secretName: {{ .Values.admin.tlsCACert.secret }}
              defaultMode: 0440
          {{- end }}
          {{- if .Values.admin.tlsClientPEM }}
          - name: tls-client-pem
            secret:
              secretName: {{ .Values.admin.tlsClientPEM.secret }}
              defaultMode: 0440
          {{- end }}
          restartPolicy: Never
{{- include "nuodb.imagePullSecrets" . | indent 10 }}
