apiVersion: "v1"
name: admin
version: 2.3.1
description: Administration tier for NuoDB.
keywords:
- nuodb
- database
- sql
home: https://github.com/nuodb/nuodb-helm-charts/tree/master/stable/admin
maintainers:
- name: NuoDB
  email: support@nuodb.com
engine: gotpl
icon: https://www.nuodb.com/sites/all/themes/nuodb/logo.svg
appVersion: 4.0.0
tillerVersion: ">=2.9"
