#!/bin/bash

# (C) Copyright NuoDB, Inc. 2019-2021  All Rights Reserved
# This file is licensed under the BSD 3-Clause License.
# See https://github.com/nuodb/nuodb-helm-charts/blob/master/LICENSE

. ${NUODB_HOME}/etc/nuodb_setup.sh

# attempt to retain the previous crash directory (within the configured window to avoid filling the disk)
crashcount=$(find $NUODB_CRASHDIR/core* -maxdepth 0 ! -type d 2>/dev/null | wc -l)
if [ $crashcount -ge 1 ]; then
  retainedcrashcount=$(find $NUODB_LOGDIR/crash-* -maxdepth 0 -type d -cmin -$OVERWRITE_WINDOW 2>/dev/null | wc -l)
  if [ $retainedcrashcount -lt $OVERWRITE_COPIES ]; then
    crashbackupdir="$NUODB_LOGDIR/crash-$( date +%Y%m%dT%H%M%S )/"
    mkdir $crashbackupdir
    mv $NUODB_CRASHDIR/core* $crashbackupdir
  fi
fi

nuodocker_flags=()
[ -n "$NUODB_DEBUG" ] && nuodocker_flags+=("--debug")

nuoserver=()
if [ -e /usr/local/bin/nuolatency.py ] ; then
    for ((i=1;i<$#;i++)); do
	if [ "${!i}" == "--admin-distribution-policy" ] ; then
            j=$((i+1))
            if [ "${!j}" == "closest" ] ; then
		server_id=$(NUOCMD_PLUGINS=/usr/local/bin/nuolatency.py nuocmd find closest-admin)
		if [ "${server_id}" != "" ] ; then
                    nuoserver+=("--server-id" $server_id)
                    # when passing server-id to nuodocker admin-distribution-policy is ignored so
                    # we don't have to remove it from $@.
		fi
            fi
	fi
	if [ "${!i}" == "--server-id" ] ; then
            # since server-id passed as argument we don't override it.
            nuoserver=()
            break
	fi
    done
fi

    
# expects NUOCMD_API_SERVER to be set.
if [ -n "${NUODB_OPTIONS}" ] ; then
    exec nuodocker "${nuodocker_flags[@]}" start te --db-name "${DB_NAME}" --options "${NUODB_OPTIONS}" "${nuoserver[@]}" "$@"
else
    exec nuodocker "${nuodocker_flags[@]}" start te --db-name "${DB_NAME}" "${nuoserver[@]}" "$@"
fi
