#!/bin/bash

# print error and exit
function die() {
  retval=$1
  shift
  echo "$@"
  exit $retval
}


processes=`nuocmd show domain --process-format "{address} {start_id}" | grep \`hostname\` | awk '{print $2}'`

if [ -z "$processes" ]
then
  die 80 "No process found"
fi

for start_id in $processes
do
  nuocmd check process --check-running --start-id $start_id || die 81 "Process reported not ready"
done
