{{- if eq (include "defaulttrue" .Values.backupmgr.restore.addRoleBinding) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "restore.serviceaccount" . | quote }}
rules:
- apiGroups:
  - "snapshot.storage.k8s.io"
  resources:
  - volumesnapshotcontents
  verbs:
  - create
{{- end }}
