apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuodb-backup-mgr-deployment
  labels:
    app: nuodb-backup-mgr
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nuodb-backup-mgr
  template:
    metadata:
      name: nuodb-backup-mgr
      labels:
        k8s-app: nuodb-backup-mgr
        name: nuodb-backup-mgr
    spec:
      serviceAccountName: nuodb-backup-manager
      containers:
      - name: logger
        command: 
        - sh
        - -c
        - "touch /var/log/backupmgr/stdout.log && tail -F /var/log/backupmgr/stdout.log"
        {{- include "aws.sidecar.setup" . | nindent 8 }}
      - name: snapshot-backups
        command: [ "/usr/local/bin/job_watch" ]
        {{- include "aws.sidecar.setup" . | nindent 8 }}
      - name: tag-snapshots
        command: [ "/usr/local/bin/snap_watch" ]
        {{- include "aws.sidecar.setup" . | nindent 8 }}
      volumes:
      - name: varlog
        emptyDir: {}
      {{- include "tls.client.volumes" . | nindent 6 }}
