{{- if and .Values.backupmgr.snapshot.serviceAccount.name (eq (include "defaulttrue" .Values.backupmgr.snapshot.addServiceAccount) "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backupmgr.snapshot.serviceAccount.name }}
  {{- with .Values.backupmgr.snapshot.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
---
{{- if and .Values.backupmgr.restore.serviceAccount.name (eq (include "defaulttrue" .Values.backupmgr.restore.addServiceAccount) "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "restore.serviceaccount" . }}
  {{- with .Values.backupmgr.restore.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
