{
 "title": "Connections",
 "tags": [
  "nuodb",
  "sql"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "host,db,pid" },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\"  WHERE db =~ /^$database$/  AND nodetype = 'Transaction' AND $timeFilter"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "SHOW TAG VALUES WITH KEY = \"db\"  "
   }
  ]
 },
 "panels": [
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"SqlListenerSqlProcTime\" WHERE (\"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Idle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"SqlListenerIdleTime\" WHERE (\"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 } },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ClientCncts",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 } },
  {
   "title": "Stall",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerStallTime",
     "query": "SELECT sum(\"value\") FROM \"SqlListenerStallTime\" WHERE (\"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerThrottleTime",
     "query": "SELECT sum(\"value\") FROM \"SqlListenerThrottleTime\" WHERE (\"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Client Connections by $group",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ClientCncts",
     "query": "SELECT mean(\"raw\") AS A FROM \"ClientCncts\" WHERE (\"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"$group\" fill(0)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Connection History",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ClientCncts",
     "query": "SELECT sum(A) FROM (SELECT mean(value) AS A FROM \"SqlListenerThrottleTime\" WHERE (nodetype = 'Transaction') AND db =~ /^$database$/ AND host =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\",\"pid\") WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerSqlProcTime",
     "query": "SELECT sum(A) FROM (SELECT mean(value) AS A FROM \"SqlListenerSqlProcTime\" WHERE (nodetype = 'Transaction') AND db =~ /^$database$/ AND host =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\",\"pid\") WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerIdleTime",
     "query": "SELECT sum(A) FROM (SELECT mean(value) AS A FROM \"SqlListenerIdleTime\" WHERE (nodetype = 'Transaction') AND db =~ /^$database$/ AND host =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\",\"pid\") WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Stalled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerIdleTime",
     "query": "SELECT sum(A) FROM (SELECT mean(value) AS A FROM \"SqlListenerStallTime\" WHERE (nodetype = 'Transaction') AND db =~ /^$database$/ AND host =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\",\"pid\") WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Throttled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerIdleTime",
     "query": "SELECT sum(A) FROM (SELECT mean(value) AS A FROM \"SqlListenerThrottleTime\" WHERE (nodetype = 'Transaction') AND db =~ /^$database$/ AND host =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\",\"pid\") WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Active Connections by $group",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerSqlProcTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Stalled Connections by $group",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerStallTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle Connections by $group",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerIdleTime",
     "query": "SELECT mean(\"value\") FROM \"SqlListenerIdleTime\" WHERE (\"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"$group\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Throttled Connections by $group",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerThrottleTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}