{
 "title": "Disk",
 "tags": [
  "nuodb",
  "disk"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"host\"\t"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"db\"\t"
   }
  ]
 },
 "panels": [
  {
   "title": "ARCHIVE STATS AVERAGED OVER ALL SMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Saves/sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsSaved",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"rate\")  AS A FROM \"ObjectsSaved\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/  AND \"db\" =~ /^$database$/ AND $timeFilter GROUP BY time(1m), \"host\" fill(null)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveQueue",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"raw\")  AS A FROM \"ArchiveQueue\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Loaded/sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsLoaded",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"rate\")  AS A FROM \"ObjectsLoaded\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "FSync",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveFsyncTime",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"value\")  AS A FROM \"ArchiveFsyncTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Directory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveDirectoryTime",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"value\")  AS A FROM \"ArchiveDirectoryTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveWriteTime",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"value\")  AS A FROM \"ArchiveWriteTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ \n AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Read",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveReadTime",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"value\")  AS A FROM \"ArchiveReadTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ \n AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Sync Throttle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveSyncThrottleTime",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"value\")  AS A FROM \"ArchiveSyncThrottleTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth Throttle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveBandwidthThrottleTime",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"value\")  AS A FROM \"ArchiveBandwidthThrottleTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveBufferedBytes",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"rate\")  AS A FROM \"DiskWritten\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  { "title": "Archive Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Objects Saved / Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host(saved)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(M) FROM (SELECT mean(\"rate\") AS M FROM \"ObjectsSaved\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host(read)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "ObjectsLoaded",
     "query": "SELECT - SUM(M) FROM (SELECT mean(\"rate\") AS M FROM \"ObjectsLoaded\" WHERE \"host\" =~ /^$host$/ AND  \"db\" =~ /^$database$/ AND(\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "FSync / Directory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host(sync)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(M) FROM (SELECT mean(\"value\") AS M FROM \"ArchiveFsyncTime\" WHERE \"host\" =~ /^$host$/  AND \"db\" =~ /^$database$/ AND (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host(directory)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT - SUM(M) FROM (SELECT mean(\"value\") AS M FROM \"ArchiveDirectoryTime\" WHERE \"host\" =~ /^$host$/  AND \"db\" =~ /^$database$/ AND (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(M) FROM (SELECT last(\"raw\") AS M FROM \"ArchiveQueue\" WHERE (\"host\" =~ /^$host$/  AND \"db\" =~ /^$database$/ AND \"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write Throttling",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WriteThrottleSetting",
     "query": "SELECT mean(B) FROM (SELECT last(\"raw\") AS B FROM \"WriteThrottleSetting\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/  AND \"db\" =~ /^$database$/ AND $timeFilter GROUP BY time($__interval) fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(M) FROM (SELECT mean(\"rate\") AS M FROM \"DiskWritten\" WHERE \"host\" =~ /^$host$/  AND \"db\" =~ /^$database$/ AND (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Journal stats averaged over all SMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Sync",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JournalFsyncTime",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"value\")  AS A FROM \"JournalFsyncTime\" WHERE \"nodetype\" = 'Storage' AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Directory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JournalDirectoryTime",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"value\")  AS A FROM \"JournalDirectoryTime\" WHERE \"nodetype\" = 'Storage' AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JournalWriteTime",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"value\")  AS A FROM \"JournalWriteTime\" WHERE \"nodetype\" = 'Storage' AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JournalQueue",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"raw\")  AS A FROM \"JournalQueue\" WHERE \"nodetype\" = 'Storage' AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JrnlBytes",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"rate\")  AS A FROM \"JrnlBytes\" WHERE \"nodetype\" = 'Storage' AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Writes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JrnlWrites",
     "query": "SELECT mean(B) FROM (SELECT last(A) AS B FROM (SELECT mean(\"rate\")  AS A FROM \"JrnlWrites\" WHERE \"nodetype\" = 'Storage' AND $timeFilter GROUP BY time(1m), \"host\" fill(none)) GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  { "title": "Journal Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(M) FROM (SELECT mean(\"raw\") AS M FROM \"JournalQueue\" WHERE \"host\" =~ /^$host$/  AND \"db\" =~ /^$database$/ AND (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sync / Directory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host(sync)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "JournalFsyncTime",
     "query": "SELECT SUM(M) FROM (SELECT mean(\"value\")*100 AS M FROM \"JournalFsyncTime\" WHERE \"host\" =~ /^$host$/  AND \"db\" =~ /^$database$/ AND (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "$tag_host(directory)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "JournalFsyncTime",
     "query": "SELECT - SUM(M) FROM (SELECT mean(\"value\")*100 AS M FROM \"JournalDirectoryTime\" WHERE \"host\" =~ /^$host$/  AND \"db\" =~ /^$database$/ AND (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  }
 ]
}