{
 "title": "NuoDB Summary",
 "tags": [ "overview" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"host\" WHERE \"nodetype\" = 'Transaction'"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "SHOW TAG VALUES WITH KEY = \"db\""
   }
  ]
 },
 "panels": [
  {
   "title": "TE Time Spent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CreatePlatformRecordsTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"CreatePlatformRecordsTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Memory GC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"MemoryThrottle\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/  AND \"db\" =~ /^$database/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PendingInsertWaitTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"PendingInsertWaitTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/  AND \"db\" =~ /^$database/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PendingUpdateWaitTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"PendingUpdateWaitTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database/  AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PlatformIndexCheckAcknowledgedTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"PlatformIndexCheckAcknowledgedTime\" WHERE (\"nodetype\" = 'Transaction') AND \"db\" =~ /^$database/ AND \"host\" =~ /^$host$/  AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PlatformObjectCheckCompleteTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"PlatformObjectCheckCompleteTime\" WHERE (\"nodetype\" = 'Transaction') AND \"db\" =~ /^$database/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PlatformObjectCheckOpenTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"PlatformObjectCheckOpenTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PlatformObjectCheckPopulatedTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"PlatformObjectCheckPopulatedTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RemoteCommitTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"RemoteCommitTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database/  AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "SqlListenerSqlProcTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"SqlListenerSqlProcTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/  AND \"db\" =~ /^$database/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total StallTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"StallPointWaitTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TransactionBlockedTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"TransactionBockedTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/  AND \"db\" =~ /^$database/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Index Insert (Split)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"WaitForSplit\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database/  AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WriteThrottleTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"value\") AS M FROM \"WriteThrottleTime\" WHERE (\"nodetype\" = 'Transaction') AND \"host\" =~ /^$host$/  AND \"db\" =~ /^$database/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stall Count Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "IdManagerBlockingStalls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"rate\") AS M FROM \"IdManagerBlockingStallCount\" WHERE (\"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter AND \"host\" =~ /^$host$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "IdManagerNonBlockingStalls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"rate\") AS M FROM \"IdManagerNonBlockingStallCount\" WHERE (\"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter AND \"host\" =~ /^$host$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PendingUpdateStalls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"rate\") AS M FROM \"PendingUpdateStallCount\" WHERE (\"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter AND \"host\" =~ /^$host$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PendingCatalogStalls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(M) FROM (SELECT mean(\"rate\") AS M FROM \"PendingCatalogStallCount\" WHERE (\"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter AND \"host\" =~ /^$host$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CurrentActiveTransactions",
     "query": "SELECT mean(A) FROM (SELECT last(raw) AS A FROM \"CurrentCommittedTransactions\" WHERE (nodetype = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\") WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CurrentActiveTransactions",
     "query": "SELECT mean(A) FROM (SELECT last(raw) AS A FROM \"CurrentActiveTransactions\" WHERE (nodetype = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\") WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Purgatory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CurrentActiveTransactions",
     "query": "SELECT mean(A) FROM (SELECT last(raw) AS A FROM \"CurrentPurgedTransactions\" WHERE (nodetype = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\") WHERE $timeFilter AND host =~ /^$host$/ GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}