---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "admin.resourceLabels" . | nindent 4 }}
  name: {{ template "admin.fullname" . }}-waitscript
data:
{{ (.Files.Glob "files/waitscript").AsConfig | indent 2 }}
{{- if .Values.admin.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "admin.resourceLabels" . | nindent 4 }}
  name: {{ template "admin.fullname" . }}-configuration
data:
{{- range $key, $val := .Values.admin.configFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "admin.resourceLabels" . | nindent 4 }}
  name: {{ template "admin.fullname" . }}-nuoadmin
data:
{{ (.Files.Glob "files/nuoadmin").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "admin.resourceLabels" . | nindent 4 }}
  name: {{ template "admin.fullname" . }}-readinessprobe
data:
{{ (.Files.Glob "files/readinessprobe").AsConfig | indent 2 }}
---
{{- if eq (include "defaulttrue" .Values.admin.livenessProbe.enabled) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "admin.resourceLabels" . | nindent 4 }}
  name: {{ template "admin.fullname" . }}-livenessprobe
data:
{{ (.Files.Glob "files/livenessprobe").AsConfig | indent 2 }}
{{- end }}
