---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "admin.fullname" . }}
    group: nuodb
    domain: {{ .Values.admin.domain }}
    chart: {{ template "admin.chart" . }}
    release: {{ .Release.Name | quote }}
  name: waitscript
data:
{{ (.Files.Glob "files/waitscript").AsConfig | indent 2 }}
{{- if .Values.admin.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "admin.fullname" . }}
    group: nuodb
    domain: {{ .Values.admin.domain }}
    chart: {{ template "admin.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ template "admin.fullname" . }}-configuration
data:
{{- range $key, $val := .Values.admin.configFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "admin.fullname" . }}
    group: nuodb
    domain: {{ .Values.admin.domain }}
    chart: {{ template "admin.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ template "admin.fullname" . }}-nuoadmin
data:
{{ (.Files.Glob "files/nuoadmin").AsConfig | indent 2 }}