{{- $rb := lookup "rbac.authorization.k8s.io/v1" "RoleBinding" (default .Release.Namespace .Values.admin.namespace) "nuodb-kube-inspector" -}}
{{- if and (eq (include "defaulttrue" .Values.nuodb.addRoleBinding) "true") (not $rb) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nuodb-kube-inspector
roleRef:
  kind: Role
  name: nuodb-kube-inspector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ default "nuodb" .Values.nuodb.serviceAccount }}
{{- end }}
