{{- if or (not (hasKey .Values.nuodb "addRoleBinding")) .Values.nuodb.addRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nuodb-kube-inspector
roleRef:
  kind: Role
  name: nuodb-kube-inspector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ default "nuodb" .Values.nuodb.serviceAccount }}
{{- end }}
