{{- if eq (include "defaulttrue" .Values.nuodb.addRoleBinding) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nuodb-kube-inspector
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - configmaps
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - create
  - update
{{- if eq (include "defaulttrue" .Values.nuodb.addClusterRoleBinding) "true" }}
{{- $namespace := default .Release.Namespace .Values.admin.namespace  | trunc 50 | trimSuffix "-" -}}
{{- $adminName := include "admin.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $namespace }}-{{ $adminName }}-nuodb-kube-inspector
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
{{- end }}
{{- end }}
