{{- if eq (include "defaulttrue" .Values.nuodb.addRoleBinding) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nuodb-kube-inspector
roleRef:
  kind: Role
  name: nuodb-kube-inspector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ default "nuodb" .Values.nuodb.serviceAccount }}
{{- if and (eq (include "defaulttrue" .Values.nuodb.addClusterRoleBinding) "true")
      (not (lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" "nuodb-kube-inspector")) }}}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nuodb-kube-inspector
roleRef:
  kind: ClusterRole
  name: nuodb-kube-inspector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ default "nuodb" .Values.nuodb.serviceAccount }}
  namespace: {{ default .Release.Namespace .Values.admin.namespace }}
{{- end }}
{{- end }}
