{{- if or (not (hasKey .Values.nuodb "addServiceAccount")) .Values.nuodb.addServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "nuodb" .Values.nuodb.serviceAccount }}
{{- end }}