{{- $sa := lookup "v1" "ServiceAccount" (default .Release.Namespace .Values.admin.namespace) .Values.nuodb.serviceAccount -}}
{{- if and .Values.nuodb.serviceAccount (eq (include "defaulttrue" .Values.nuodb.addServiceAccount) "true") (not $sa) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nuodb.serviceAccount }}
{{- end }}