apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  annotations:
    description: |-
      NuoAdmin statefulset resource for NuoDB Admin layer.
    kubectl.kubernetes.io/default-container: admin
    kubectl.kubernetes.io/default-logs-container: admin
{{- include "admin.loadBalancerConfig" . | indent 4 }}
    {{- if (eq (default "cluster0" .Values.cloud.cluster.name) (default "cluster0" .Values.cloud.cluster.entrypointName)) }}
    nuodb.com/bootstrap-servers: {{ default 0 .Values.admin.bootstrapServers | quote }}
    {{- end }}
  labels:
    {{- include "admin.resourceLabels" . | nindent 4 }}
    component: admin
    {{- if (eq (default "cluster0" .Values.cloud.cluster.name) (default "cluster0" .Values.cloud.cluster.entrypointName)) }}
    bootstrapServers: {{ default 0 .Values.admin.bootstrapServers | quote }}
    {{- end }}
  name: {{ template "admin.fullname" . }}
spec:
  serviceName: {{ .Values.admin.domain }}
  podManagementPolicy: Parallel
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app: {{ template "admin.fullname" . }}
      component: admin
  template:
    metadata:
      name: {{ template "admin.fullname" . }}
      annotations:
      {{- if .Values.admin.configFiles }}
        {{- with .Values.admin.configFiles }}
        checksum/config: {{ toYaml . | sha256sum }}
        {{- end }}
      {{- else }}
        checksum/config: "0"
      {{- end }}
      {{- include "admin.tlsConfigAnnotations" . | nindent 8 }}
      {{- if .Values.admin.podAnnotations }}
{{ toYaml .Values.admin.podAnnotations | trim | indent 8}}
      {{- end }}
      labels:
        {{- include "admin.resourceLabels" . | nindent 8 }}
        component: admin
    spec:
      serviceAccountName: {{ default "" .Values.nuodb.serviceAccount }}
      priorityClassName: {{ default "" .Values.admin.priorityClass }}
      {{- include "securityContext" . | indent 6 }}
      {{- with .Values.admin.nodeSelector }}
      nodeSelector:
{{ toYaml . | trim | indent 8 }}
      {{- end }}
{{- if .Values.admin.affinity }}
      affinity:
{{ tpl .Values.admin.affinity . | trim | indent 8 }}
{{- end }}
      {{- if .Values.admin.tolerations }}
      tolerations:
{{ toYaml .Values.admin.tolerations | trim | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 15
      {{- if eq (include "defaulttrue" .Values.admin.initContainers.runInitDisk) "true" }}
      initContainers:
      - name: init-disk
        image: {{ template "init.image" . }}
        imagePullPolicy: {{ default "" .Values.busybox.image.pullPolicy }}
        command:
          - sh
          - -c
          - find /mnt/* -maxdepth 1 -not \( -perm -0770 -user 1000 \) -exec chmod -R ug+rwx {} \; -exec chown -R 1000 {} \; -exec echo {} \;
        volumeMounts:
        - name: raftlog
          mountPath: /mnt/vardir
        {{- if eq (include "defaultfalse" .Values.admin.logPersistence.enabled) "true" }}
        - name: log-volume
          mountPath: /mnt/logdir
        {{- end }}
        {{- if eq (include "admin.enableEphemeralVolume" .) "true" }}
        - name: eph-volume
          mountPath: /mnt/eph
        {{- end }}
        {{- if eq (include "defaulttrue" .Values.admin.initContainers.runInitDiskAsRoot) "true" }}
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        {{- end }}
      {{- end }}
      containers:
      - name: admin
        image: {{ template "nuodb.image" . }}
        imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
        ports:
        - { containerPort: 8888,  protocol: TCP }
        - { containerPort: 48004, protocol: TCP }
        - { containerPort: 48005, protocol: TCP }
        resources:
{{ toYaml .Values.admin.resources | trim | indent 10 }}
    {{- include "admin.envFrom" . | indent 8 }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - { name: NUODB_DOMAIN_ENTRYPOINT, value: "{{ template "nuodb.domainEntrypoint" . }}" }
        - { name: NUODB_ALT_ADDRESS,       value: "{{ template "nuodb.altAddress" . }}" }
        - { name: NUODB_VARDIR,            value: "/var/opt/nuodb/$(POD_NAME).$(NAMESPACE)" }
        - { name: COMPONENT_NAME,          value: "admin" }
        - { name: OVERWRITE_COPIES,    value: "{{ .Values.admin.logPersistence.overwriteBackoff.copies | default "3" }}" }
        - { name: OVERWRITE_WINDOW,    value: "{{ .Values.admin.logPersistence.overwriteBackoff.windowMinutes | default "120" }}" }
        {{- if .Values.admin.tlsKeyStore }}
        {{- if .Values.admin.tlsKeyStore.password }}
        - { name: NUODB_KEYSTORE_PASSWORD,    value: {{ .Values.admin.tlsKeyStore.password | quote }} }
        {{- else }}
        - name: NUODB_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.admin.tlsKeyStore.secret }}
              key: {{ .Values.admin.tlsKeyStore.passwordKey | default "password" }}
        {{- end }}
        {{- end }}
        {{- if .Values.admin.tlsTrustStore }}
        {{- if .Values.admin.tlsTrustStore.password }}
        - { name: NUODB_TRUSTSTORE_PASSWORD,  value: {{ .Values.admin.tlsTrustStore.password | quote }} }
        {{- else }}
        - name: NUODB_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.admin.tlsTrustStore.secret }}
              key: {{ .Values.admin.tlsTrustStore.passwordKey | default "password" }}
        {{- end }}
        {{- end }}
        {{- if eq (include "defaultfalse" .Values.admin.securityContext.enabledOnContainer) "true" }}
        {{- if eq (include "defaultfalse" .Values.admin.securityContext.readOnlyRootFilesystem) "true" }}
        - { name: NUODOCKER_CONF_DIR, value: "/tmp"}
        {{- end }}
        {{- end }}
        args:
          - "nuoadmin"
          {{- if .Values.admin.evicted}}
          {{- if .Values.admin.evicted.servers}}
          - "--evicted-servers"
          - "{{ include "helm-toolkit.utils.joinListWithComma" .Values.admin.evicted.servers }}"
          {{- end }}
          {{- end }}
          - "--"
          {{- if .Values.admin.tde }}
          {{- if and .Values.admin.tde.storagePasswordsDir (ne .Values.admin.tde.storagePasswordsDir "/etc/nuodb/tde") }}
          - "tdeMonitor.storagePasswordsDir={{ .Values.admin.tde.storagePasswordsDir }}"
          {{- end }}
          {{- end }}
          {{- if .Values.admin.license.secret }}
          - "licenseFilePath={{ .Values.admin.configFilesPath }}/license/nuodb.lic"
          {{- end }}
          {{- range $opt, $val := .Values.admin.options}}
          - "{{$opt}}={{$val}}" 
          {{- end }}
        {{- include "sc.containerSecurityContext" . | indent 8 }}
        {{- if eq (include "defaulttrue" .Values.admin.livenessProbe.enabled) "true" }}
        livenessProbe:
          initialDelaySeconds: {{ default 60 .Values.admin.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 60 .Values.admin.livenessProbe.periodSeconds }}
          failureThreshold: {{ default 10 .Values.admin.livenessProbe.failureThreshold }}
          exec:
            command: [ "livenessprobe" ]
          timeoutSeconds: {{ default 20 .Values.admin.livenessProbe.timeoutSeconds }}
        {{- end }}
        readinessProbe:
          initialDelaySeconds: {{ default 10 .Values.admin.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 15 .Values.admin.readinessProbe.periodSeconds }}
          failureThreshold: {{ default 4 .Values.admin.readinessProbe.failureThreshold }}
          successThreshold: {{ default 1 .Values.admin.readinessProbe.successThreshold }}
          exec:
            command: [ "readinessprobe" ]
          timeoutSeconds: {{ include "admin.readinessTimeoutSeconds" . }}
        volumeMounts:
        - mountPath: /var/log/nuodb
          {{- if eq (include "defaultfalse" .Values.admin.logPersistence.enabled) "true" }}
          name: log-volume
          {{- else }}
          name: eph-volume
          subPath: log
          {{- end }}
        {{- if eq (include "admin.enableEphemeralVolume" .) "true" }}
        - mountPath: /tmp
          name: eph-volume
          subPath: tmp
        {{- end }}
        {{- with .Values.admin.configFiles }}
        {{- range $key, $val := . }}
        - name: configurations
          mountPath: {{ $.Values.admin.configFilesPath }}/{{ $key }}
          subPath: {{ $key }}
        {{- end -}}
        {{- end }}
        {{- if .Values.admin.license.secret }}
        - name: license
          mountPath: {{ .Values.admin.configFilesPath }}/license
          readOnly: true
        {{- end }}
        - name: raftlog
          mountPath: /var/opt/nuodb
        - name: nuoadmin
          mountPath: /usr/local/bin/nuoadmin
          subPath: nuoadmin
        - name: readinessprobe
          mountPath: /usr/local/bin/readinessprobe
          subPath: readinessprobe
        {{- if eq (include "defaulttrue" .Values.admin.livenessProbe.enabled) "true" }}
        - name: livenessprobe
          mountPath: /usr/local/bin/livenessprobe
          subPath: livenessprobe
        {{- end }}
        {{- if .Values.admin.tlsKeyStore }}
        - name: tls
          mountPath: /etc/nuodb/keys
          readOnly: true
        {{- end }}
        {{- if .Values.admin.tde }}
        {{- if .Values.admin.tde.secrets }}
        {{- range $dbName, $secret := .Values.admin.tde.secrets }}
        - name: tde-volume-{{ $dbName }}
          mountPath: {{ default "/etc/nuodb/tde" $.Values.admin.tde.storagePasswordsDir }}/{{ $dbName }}
          readOnly: true
        {{- end }}
        {{- end }}
        {{- end }}
      {{- include "nuodb.sidecar.collector" . | nindent 6 }}
      {{- include "nuodb.imagePullSecrets" . | indent 6 }}
      volumes:
      {{- if .Values.admin.tde }}
      {{- if .Values.admin.tde.secrets }}
      {{- range $dbName, $secret := .Values.admin.tde.secrets }}
      - name: tde-volume-{{ $dbName }}
        secret:
          secretName: {{ $secret }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- include "admin.tlsVolume" . | nindent 6 }}
      {{- if eq (include "admin.enableEphemeralVolume" .) "true" }}
      - name: eph-volume
        {{- include "admin.ephemeralVolume" . | indent 8 }}
      {{- end }}
      {{- if .Values.admin.configFiles }}
      - name: configurations
        configMap:
          name: {{ template "admin.fullname" . }}-configuration
      {{- end }}
      {{- if .Values.admin.license.secret }}
      - name: license
        secret:
          secretName: {{ .Values.admin.license.secret }}
          defaultMode: 0440
          items:
            - key: {{ .Values.admin.license.key }}
              path: nuodb.lic
      {{- end }}
      - name: nuoadmin
        configMap:
          name: {{ template "admin.fullname" . }}-nuoadmin
          defaultMode: 0755
      - name: readinessprobe
        configMap:
          name: {{ template "admin.fullname" . }}-readinessprobe
          defaultMode: 0755
      {{- if eq (include "defaulttrue" .Values.admin.livenessProbe.enabled) "true" }}
      - name: livenessprobe
        configMap:
          name: {{ template "admin.fullname" . }}-livenessprobe
          defaultMode: 0755
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: raftlog
      labels:
        {{- include "admin.resourceLabels" . | nindent 8 }}
    spec:
    {{- if .Values.admin.persistence.storageClass }}
      {{- if (eq "-" .Values.admin.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.admin.persistence.storageClass }}
      {{- end }}
    {{- end }}
      accessModes:
      {{- range .Values.admin.persistence.accessModes }}
        - {{ . }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.admin.persistence.size }}
{{- if eq (include "defaultfalse" .Values.admin.logPersistence.enabled) "true" }}
  - metadata:
      name: log-volume
      labels:
        {{- include "admin.resourceLabels" . | nindent 8 }}
    spec:
    {{- if .Values.admin.logPersistence.storageClass }}
      {{- if (eq "-" .Values.admin.logPersistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.admin.logPersistence.storageClass }}
      {{- end }}
    {{- end }}
      accessModes:
      {{- range .Values.admin.logPersistence.accessModes }}
        - {{ . }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.admin.logPersistence.size }}
{{- end }}
