apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuodb-helm-repo
  labels:
    app.kubernetes.io/name: nuodb-helm-repo
    app.kubernetes.io/instance: nuodb-helm-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nuodb-helm-repo
      app.kubernetes.io/instance: nuodb-helm-repo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nuodb-helm-repo
        app.kubernetes.io/instance: nuodb-helm-repo
    spec:
      securityContext:
        {}
      containers:
        - name: nginx
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: charts-volume
      volumes:
      - name: charts-volume
        configMap:
          name: charts
          defaultMode: 0644