apiVersion: v1
kind: Service
metadata:
  name: nuodb-helm-repo
  labels:
    app.kubernetes.io/name: nuodb-helm-repo
    app.kubernetes.io/instance: nuodb-helm-repo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nuodb-helm-repo
    app.kubernetes.io/instance: nuodb-helm-repo