#!/usr/bin/env ruby
 
require "erb"
require "ostruct"
require "yaml"

REPO_URL = 'https://nuodb-charts.storage.googleapis.com/'

class Chart < OpenStruct
  def initialize(source)
    @to_str = source
    super(YAML.load_file(source))
  end

  def self.all
    @all ||= Dir["../**/Chart.yaml"].map { |source| new(source) }
  end

  def self.targets
    all.map(&:target)
  end

  def self.from_target(target)
    all.detect { |chart| target == chart.target }
  end

  attr_reader :to_str

  def target
    "#{WEB_ROOT}/#{name}-#{version}.tgz"
  end
end

puts "Creating index..."
File.write("index.html", ERB.new(File.read("scripts/index.html.erb")).result)

puts "Index created, checkin the index to complete:"
puts "\n\t$ git checkout gh-pages\n\t$ git add index.html\n\t$ git commit -m \"update index\"\n\t$ git push\n\n"
