#!/usr/bin/env bash

set -o errexit
set -o pipefail

# VERSION=1.3.0 scripts/ci/tag

: ${VERSION:?"Specify <major.minor> version for release, e.g 1.2.3"}

GIT_TAG=v${VERSION}

main() {
  version
  push_version

  tag
  push_tag

  branch
  push_branch
}

version () {
  echo "Updating Helm chart versions..."
  find stable -type f -name Chart.yaml -exec sed -i "" "s/version: .*/version: ${VERSION}/g" {} \;
  find incubator -type f -name Chart.yaml -exec sed -i "" "s/version: .*/version: ${VERSION}/g" {} \;
  sed -i "" "s/future-release=.*/future-release=${VERSION}/g" .github_changelog_generator
  git add -u
  git commit -m "Release ${VERSION}"
}

push_version () {
  echo "Pushing Chart version..."
  git push
}

tag () {
  echo "Adding Git tag..."
  git tag -a ${GIT_TAG} -m "${GIT_TAG}"
}

push_tag () {
  echo "Pushing Git tag..."
  git push origin ${GIT_TAG}
}

branch () {
  echo "Adding Git branch..."
  git branch ${GIT_TAG}-rel ${GIT_TAG}
}

push_branch () {
  echo "Pushing Git branch..."
  git push --set-upstream origin ${GIT_TAG}-rel
}

main
