{{- if eq (include "defaulttrue" .Values.database.primaryRelease) "true" }}
{{- if eq (include "defaulttrue" .Values.database.sm.hotCopy.enablePod) "true" }}
{{- if eq (include "defaulttrue" .Values.database.sm.hotCopy.enableBackups) "true" }}
{{- $globalScope := . -}}
{{- $backupGroups := list -}}
{{- if .Values.database.sm.hotCopy.backupGroups -}}
  {{- $backupGroups = (keys .Values.database.sm.hotCopy.backupGroups) | sortAlpha -}}
{{- else -}}
  {{- range $i, $e := until (.Values.database.sm.hotCopy.replicas | int) -}}
    {{- $backupGroups = append $backupGroups (printf "%s-%d" (include "hotcopy.groupPrefix" $globalScope) $i) -}}
  {{- end -}}
{{- end -}}
{{- range $i, $backupGroup := $backupGroups -}}
  {{- with $globalScope }}
    {{ $backupGroupLabels := include "hotcopy.group.labels" (merge (dict "backupGroup" $backupGroup) .) }}
---
apiVersion: {{ include "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ include "hotcopy.cronjob.name" (merge (dict "backupGroup" $backupGroup "hotCopyType" "full") . ) }}
  labels:
    {{- include "database.resourceLabels" . | nindent 4 }}
    subgroup: backup
    backup-group: {{ $backupGroup }}
spec:
  schedule: {{ include "hotcopy.group.schedule" (merge (dict "backupGroup" $backupGroup "hotCopyType" "full") . ) }}
  startingDeadlineSeconds: {{ .Values.database.sm.hotCopy.deadline}}
  successfulJobsHistoryLimit: {{ .Values.database.sm.hotCopy.successHistory}}
  failedJobsHistoryLimit: {{ .Values.database.sm.hotCopy.failureHistory}}
  jobTemplate:
    metadata:
      annotations:
        backup-group-labels: "{{ $backupGroupLabels }}"
        operation: full-hotcopy
      labels:
        {{- include "database.resourceLabels" . | nindent 8 }}
        subgroup: backup
        backup-group: {{ $backupGroup }}
    spec:
      template:
        metadata:
          annotations:
            backup-group-labels: "{{ $backupGroupLabels }}"
            operation: full-hotcopy
          labels:
            {{- include "database.resourceLabels" . | nindent 12 }}
            subgroup: backup
            backup-group: {{ $backupGroup }}
        spec:
          {{- include "securityContext" . | indent 10 }}
          containers:
          - name: nuodb
            image: {{ template "nuodb.image" . }}
            imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
            args:
            - "nuobackup"
            - "--type"
            - "full"
            - "--db-name"
            - "{{ .Values.database.name }}"
            - "--group"
            - "{{ $backupGroup }}"
            - "--timeout"
            - "{{ .Values.database.sm.hotCopy.timeout }}"      
            - "--backup-root"
            - "{{ .Values.database.sm.hotCopy.backupDir }}"
            {{- if $backupGroupLabels }}
            - "--labels"
            - "{{ $backupGroupLabels }}"
            {{- end }}
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - { name: DB_NAME,             value: "{{ .Values.database.name }}"     }
            - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888" }
            - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
            - { name: BACKUP_DIR,          value: "{{ .Values.database.sm.hotCopy.backupDir }}" }
            {{- include "sc.containerSecurityContext" . | indent 12 }}
            resources:
            {{- toYaml .Values.database.sm.hotCopy.jobResources | trim | nindent 14 }}
            volumeMounts:
            - name: nuobackup
              mountPath: /usr/local/bin/nuobackup
              subPath: nuobackup
            {{- if .Values.admin.tlsCACert }}
            - name: tls-ca-cert
              mountPath: /etc/nuodb/keys/ca.cert
              subPath: {{ .Values.admin.tlsCACert.key }}
            {{- end }}
            {{- if .Values.admin.tlsClientPEM }}
            - name: tls-client-pem
              mountPath: /etc/nuodb/keys/nuocmd.pem
              subPath: {{ .Values.admin.tlsClientPEM.key }}
            {{- end }}
          volumes:
          - name: nuobackup
            configMap:
              name: {{ template "database.fullname" . }}-nuobackup
              defaultMode: 0777
          {{- if .Values.admin.tlsCACert }}
          - name: tls-ca-cert
            secret:
              secretName: {{ .Values.admin.tlsCACert.secret }}
              defaultMode: 0440
          {{- end }}
          {{- if .Values.admin.tlsClientPEM }}
          - name: tls-client-pem
            secret:
              secretName: {{ .Values.admin.tlsClientPEM.secret }}
              defaultMode: 0440
          {{- end }}
          restartPolicy: {{ .Values.database.sm.hotCopy.restartPolicy }}
{{- include "nuodb.imagePullSecrets" . | indent 10 }}
---
apiVersion: {{ include "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ include "hotcopy.cronjob.name" (merge (dict "backupGroup" $backupGroup "hotCopyType" "incremental") . ) }}
  annotations:
    backup-group-labels: "{{ $backupGroupLabels }}"
    operation: full-hotcopy
  labels:
    {{- include "database.resourceLabels" . | nindent 4 }}
    subgroup: backup
    backup-group: {{ $backupGroup }}
spec:
  schedule: {{ include "hotcopy.group.schedule" (merge (dict "backupGroup" $backupGroup "hotCopyType" "incremental") . ) }}
  startingDeadlineSeconds: {{ .Values.database.sm.hotCopy.deadline}}
  successfulJobsHistoryLimit: {{ .Values.database.sm.hotCopy.successHistory}}
  failedJobsHistoryLimit: {{ .Values.database.sm.hotCopy.failureHistory}}
  jobTemplate:
    metadata:
      annotations:
        backup-group-labels: "{{ $backupGroupLabels }}"
        operation: incremental-hotcopy
      labels:
        {{- include "database.resourceLabels" . | nindent 8 }}
        subgroup: backup
        backup-group: {{ $backupGroup }}
    spec:
      template:
        spec:
          {{- include "securityContext" . | indent 10 }}
          containers:
          - name: nuodb
            image: {{ template "nuodb.image" . }}
            imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
            args:
            - "nuobackup"
            - "--type"
            - "incremental"
            - "--db-name"
            - "{{ .Values.database.name }}"
            - "--group"
            - "{{ $backupGroup }}"
            - "--timeout"
            - "{{ .Values.database.sm.hotCopy.timeout }}"      
            - "--backup-root"
            - "{{ .Values.database.sm.hotCopy.backupDir }}"
            {{- if $backupGroupLabels }}
            - "--labels"
            - "{{ $backupGroupLabels }}"
            {{- end }}
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - { name: DB_NAME,             value: "{{ .Values.database.name }}"     }
            - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888" }
            - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
            - { name: BACKUP_DIR,          value: "{{ .Values.database.sm.hotCopy.backupDir }}" }
            {{- include "sc.containerSecurityContext" . | indent 12 }}
            resources:
            {{- toYaml .Values.database.sm.hotCopy.jobResources | trim | nindent 14 }}
            volumeMounts:
            - name: nuobackup
              mountPath: /usr/local/bin/nuobackup
              subPath: nuobackup
            {{- if .Values.admin.tlsCACert }}
            - name: tls-ca-cert
              mountPath: /etc/nuodb/keys/ca.cert
              subPath: {{ .Values.admin.tlsCACert.key }}
            {{- end }}
            {{- if .Values.admin.tlsClientPEM }}
            - name: tls-client-pem
              mountPath: /etc/nuodb/keys/nuocmd.pem
              subPath: {{ .Values.admin.tlsClientPEM.key }}
            {{- end }}
          volumes:
          - name: nuobackup
            configMap:
              name: {{ template "database.fullname" . }}-nuobackup
              defaultMode: 0777
          {{- if .Values.admin.tlsCACert }}
          - name: tls-ca-cert
            secret:
              secretName: {{ .Values.admin.tlsCACert.secret }}
              defaultMode: 0440
          {{- end }}
          {{- if .Values.admin.tlsClientPEM }}
          - name: tls-client-pem
            secret:
              secretName: {{ .Values.admin.tlsClientPEM.secret }}
              defaultMode: 0440
          {{- end }}
          restartPolicy: {{ .Values.database.sm.hotCopy.restartPolicy }}
{{- include "nuodb.imagePullSecrets" . | indent 10 }}

{{- if eq (include "defaultfalse" .Values.database.sm.hotCopy.journalBackup.enabled) "true" }}
---
apiVersion: {{ include "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ include "hotcopy.cronjob.name" (merge (dict "backupGroup" $backupGroup "hotCopyType" "journal") . ) }}
  annotations:
    backup-group-labels: "{{ $backupGroupLabels }}"
    operation: journal-hotcopy
  labels:
    {{- include "database.resourceLabels" . | nindent 4 }}
    subgroup: backup
    backup-group: {{ $backupGroup }}
    backup-group-labels: "{{ $backupGroupLabels }}"
spec:
  schedule: {{ include "hotcopy.group.schedule" (merge (dict "backupGroup" $backupGroup "hotCopyType" "journal") . ) }}
  startingDeadlineSeconds: {{ .Values.database.sm.hotCopy.journalBackup.deadline }}
  successfulJobsHistoryLimit: {{ .Values.database.sm.hotCopy.successHistory }}
  failedJobsHistoryLimit: {{ .Values.database.sm.hotCopy.failureHistory }}
  jobTemplate:
    metadata:
      labels:
        {{- include "database.resourceLabels" . | nindent 8 }}
        subgroup: backup
        backup-group: {{ $backupGroup }}
    spec:
      template:
        metadata:
          annotations:
            backup-group-labels: "{{ $backupGroupLabels }}"
            operation: journal-hotcopy
          labels:
            {{- include "database.resourceLabels" . | nindent 12 }}
            subgroup: backup
            backup-group: "{{ $backupGroup }}"
        spec:
          {{- include "securityContext" . | indent 10 }}
          containers:
          - name: nuodb
            image: {{ template "nuodb.image" . }}
            imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
            args:
            - "nuobackup"
            - "--type"
            - "journal"
            - "--db-name"
            - "{{ .Values.database.name }}"
            - "--group"
            - "{{ $backupGroup }}"
            - "--timeout"
            - "{{ .Values.database.sm.hotCopy.journalBackup.timeout }}"      
            - "--backup-root"
            - "{{ .Values.database.sm.hotCopy.backupDir }}"
            {{- if $backupGroupLabels }}
            - "--labels"
            - "{{ $backupGroupLabels }}"
            {{- end }}
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - { name: DB_NAME,             value: "{{ .Values.database.name }}"     }
            - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888" }
            - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
            - { name: BACKUP_DIR,          value: "{{ .Values.database.sm.hotCopy.backupDir }}" }
            {{- include "sc.containerSecurityContext" . | indent 12 }}
            resources:
            {{- toYaml .Values.database.sm.hotCopy.jobResources | trim | nindent 14 }}
            volumeMounts:
            - name: nuobackup
              mountPath: /usr/local/bin/nuobackup
              subPath: nuobackup
            {{- if .Values.admin.tlsCACert }}
            - name: tls-ca-cert
              mountPath: /etc/nuodb/keys/ca.cert
              subPath: {{ .Values.admin.tlsCACert.key }}
            {{- end }}
            {{- if .Values.admin.tlsClientPEM }}
            - name: tls-client-pem
              mountPath: /etc/nuodb/keys/nuocmd.pem
              subPath: {{ .Values.admin.tlsClientPEM.key }}
            {{- end }}
          volumes:
          - name: nuobackup
            configMap:
              name: {{ template "database.fullname" . }}-nuobackup
              defaultMode: 0777
          {{- if .Values.admin.tlsCACert }}
          - name: tls-ca-cert
            secret:
              secretName: {{ .Values.admin.tlsCACert.secret }}
              defaultMode: 0440
          {{- end }}
          {{- if .Values.admin.tlsClientPEM }}
          - name: tls-client-pem
            secret:
              secretName: {{ .Values.admin.tlsClientPEM.secret }}
              defaultMode: 0440
          {{- end }}
          restartPolicy: {{ .Values.database.sm.hotCopy.restartPolicy }}
{{- include "nuodb.imagePullSecrets" . | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
