{{- if .Values.database.sm.hotCopy.enablePod }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: full-hotcopy-{{ .Values.database.name }}-cronjob
  labels:
    group: nuodb
    subgroup: backup
    database: {{ .Values.database.name }}
spec:
  schedule: {{ .Values.database.sm.hotCopy.fullSchedule}}
  startingDeadlineSeconds: {{ .Values.database.sm.hotCopy.deadline}}
  successfulJobsHistoryLimit: {{ .Values.database.sm.hotCopy.successHistory}}
  failedJobsHistoryLimit: {{ .Values.database.sm.hotCopy.failureHistory}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nuodb
            image: {{ template "nuodb.image" . }}
            imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
            args:
            - "nuobackup"
            - "--type"
            - "full"
            - "--db-name"
            - "{{ .Values.database.name }}"
            - "--group"
            - "{{ include "hotcopy.group" . }}"
            - "--timeout"
            - "{{ .Values.database.sm.hotCopy.timeout }}"      
            - "--backup-root"
            - "{{ .Values.database.sm.hotCopy.backupDir }}"
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - { name: DB_NAME,             value: "{{ .Values.database.name }}"     }
            - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888" }
            - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
            - { name: TIMEOUT,             value: "{{ .Values.database.sm.hotCopy.timeout }}" }
            - { name: BACKUP_DIR,          value: "{{ .Values.database.sm.hotCopy.backupDir }}" }
            volumeMounts:
            - name: nuobackup
              mountPath: /usr/local/bin/nuobackup
              subPath: nuobackup
            {{- if .Values.admin.tlsCACert }}
            - name: tls-ca-cert
              mountPath: /etc/nuodb/keys/ca.cert
              subPath: {{ .Values.admin.tlsCACert.key }}
            {{- end }}
            {{- if .Values.admin.tlsClientPEM }}
            - name: tls-client-pem
              mountPath: /etc/nuodb/keys/nuocmd.pem
              subPath: {{ .Values.admin.tlsClientPEM.key }}
            {{- end }}
          volumes:
          - name: nuobackup
            configMap:
              name: {{ template "database.fullname" . }}-nuobackup
              defaultMode: 0777
          {{- if .Values.admin.tlsCACert }}
          - name: tls-ca-cert
            secret:
              secretName: {{ .Values.admin.tlsCACert.secret }}
              defaultMode: 0440
          {{- end }}
          {{- if .Values.admin.tlsClientPEM }}
          - name: tls-client-pem
            secret:
              secretName: {{ .Values.admin.tlsClientPEM.secret }}
              defaultMode: 0440
          {{- end }}
          restartPolicy: Never
{{- include "nuodb.imagePullSecrets" . | indent 10 }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: post-restore-{{ .Values.database.name }}-cronjob
  labels:
    group: nuodb
    subgroup: backup
    database: {{ .Values.database.name }}
spec:
  schedule: "?/3 * * * *"
  startingDeadlineSeconds: {{ .Values.database.sm.hotCopy.deadline }}
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: {{ .Values.database.sm.hotCopy.failureHistory }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nuodb
            image: {{ template "nuodb.image" . }}
            imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
            args:
            - "nuobackup"
            - "--type"
            - "full"
            - "--db-name"
            - "{{ .Values.database.name }}"
            - "--group"
            - "{{ include "hotcopy.group" . }}"
            - "--semaphore"
            - "/nuobackup/semaphore"
            - "--timeout"
            - "{{ .Values.database.sm.hotCopy.timeout }}"      
            - "--backup-root"
            - "{{ .Values.database.sm.hotCopy.backupDir }}"
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - { name: DB_NAME,             value: "{{ .Values.database.name }}"     }
            - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888" }
            - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
            - { name: TIMEOUT,             value: "{{ .Values.database.sm.hotCopy.timeout }}" }
            - { name: BACKUP_DIR,          value: "{{ .Values.database.sm.hotCopy.backupDir }}" }
            volumeMounts:
            - name: nuobackup
              mountPath: /usr/local/bin/nuobackup
              subPath: nuobackup
            {{- if .Values.admin.tlsCACert }}
            - name: tls-ca-cert
              mountPath: /etc/nuodb/keys/ca.cert
              subPath: {{ .Values.admin.tlsCACert.key }}
            {{- end }}
            {{- if .Values.admin.tlsClientPEM }}
            - name: tls-client-pem
              mountPath: /etc/nuodb/keys/nuocmd.pem
              subPath: {{ .Values.admin.tlsClientPEM.key }}
            {{- end }}
          volumes:
          - name: nuobackup
            configMap:
              name: {{ template "database.fullname" . }}-nuobackup
              defaultMode: 0777
          {{- if .Values.admin.tlsCACert }}
          - name: tls-ca-cert
            secret:
              secretName: {{ .Values.admin.tlsCACert.secret }}
              defaultMode: 0440
          {{- end }}
          {{- if .Values.admin.tlsClientPEM }}
          - name: tls-client-pem
            secret:
              secretName: {{ .Values.admin.tlsClientPEM.secret }}
              defaultMode: 0440
          {{- end }}
          restartPolicy: Never
{{- include "nuodb.imagePullSecrets" . | indent 10 }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: incremental-hotcopy-{{ .Values.database.name }}-cronjob
  labels:
    group: nuodb
    subgroup: backup
    database: {{ .Values.database.name }}
spec:
  schedule: {{ .Values.database.sm.hotCopy.incrementalSchedule}}
  startingDeadlineSeconds: {{ .Values.database.sm.hotCopy.deadline}}
  successfulJobsHistoryLimit: {{ .Values.database.sm.hotCopy.successHistory}}
  failedJobsHistoryLimit: {{ .Values.database.sm.hotCopy.failureHistory}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nuodb
            image: {{ template "nuodb.image" . }}
            imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
            args:
            - "nuobackup"
            - "--type"
            - "incremental"
            - "--db-name"
            - "{{ .Values.database.name }}"
            - "--group"
            - "{{ include "hotcopy.group" . }}"
            - "--timeout"
            - "{{ .Values.database.sm.hotCopy.timeout }}"      
            - "--backup-root"
            - "{{ .Values.database.sm.hotCopy.backupDir }}"
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - { name: DB_NAME,             value: "{{ .Values.database.name }}"     }
            - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888" }
            - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
            - { name: TIMEOUT,             value: "{{ .Values.database.sm.hotCopy.timeout }}" }
            - { name: BACKUP_DIR,          value: "{{ .Values.database.sm.hotCopy.backupDir }}" }
            volumeMounts:
            - name: nuobackup
              mountPath: /usr/local/bin/nuobackup
              subPath: nuobackup
            {{- if .Values.admin.tlsCACert }}
            - name: tls-ca-cert
              mountPath: /etc/nuodb/keys/ca.cert
              subPath: {{ .Values.admin.tlsCACert.key }}
            {{- end }}
            {{- if .Values.admin.tlsClientPEM }}
            - name: tls-client-pem
              mountPath: /etc/nuodb/keys/nuocmd.pem
              subPath: {{ .Values.admin.tlsClientPEM.key }}
            {{- end }}
          volumes:
          - name: nuobackup
            configMap:
              name: {{ template "database.fullname" . }}-nuobackup
              defaultMode: 0777
          {{- if .Values.admin.tlsCACert }}
          - name: tls-ca-cert
            secret:
              secretName: {{ .Values.admin.tlsCACert.secret }}
              defaultMode: 0440
          {{- end }}
          {{- if .Values.admin.tlsClientPEM }}
          - name: tls-client-pem
            secret:
              secretName: {{ .Values.admin.tlsClientPEM.secret }}
              defaultMode: 0440
          {{- end }}
          restartPolicy: Never
{{- include "nuodb.imagePullSecrets" . | indent 10 }}

{{- if .Values.database.sm.hotCopy.journalBackup.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: journal-hotcopy-{{ .Values.database.name }}-cronjob
  labels:
    group: nuodb
    subgroup: backup
    database: {{ .Values.database.name }}
spec:
  schedule: "?/{{ .Values.database.sm.hotCopy.journalBackup.intervalMinutes }} * * * *"
  startingDeadlineSeconds: {{ .Values.database.sm.hotCopy.journalBackup.deadline }}
  successfulJobsHistoryLimit: {{ .Values.database.sm.hotCopy.successHistory }}
  failedJobsHistoryLimit: {{ .Values.database.sm.hotCopy.failureHistory }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nuodb
            image: {{ template "nuodb.image" . }}
            imagePullPolicy: {{ .Values.nuodb.image.pullPolicy }}
            args:
            - "nuobackup"
            - "--type"
            - "journal"
            - "--db-name"
            - "{{ .Values.database.name }}"
            - "--group"
            - "{{ include "hotcopy.group" . }}"
            - "--timeout"
            - "{{ .Values.database.sm.hotCopy.timeout }}"      
            - "--backup-root"
            - "{{ .Values.database.sm.hotCopy.backupDir }}"
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - { name: DB_NAME,             value: "{{ .Values.database.name }}"     }
            - { name: NUOCMD_API_SERVER,   value: "{{ template "admin.address" . }}:8888" }
            - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
            - { name: TIMEOUT,             value: "{{ .Values.database.sm.hotCopy.journalBackup.timeout }}" }
            - { name: BACKUP_DIR,          value: "{{ .Values.database.sm.hotCopy.backupDir }}" }
            volumeMounts:
            - name: nuobackup
              mountPath: /usr/local/bin/nuobackup
              subPath: nuobackup
            {{- if .Values.admin.tlsCACert }}
            - name: tls-ca-cert
              mountPath: /etc/nuodb/keys/ca.cert
              subPath: {{ .Values.admin.tlsCACert.key }}
            {{- end }}
            {{- if .Values.admin.tlsClientPEM }}
            - name: tls-client-pem
              mountPath: /etc/nuodb/keys/nuocmd.pem
              subPath: {{ .Values.admin.tlsClientPEM.key }}
            {{- end }}
          volumes:
          - name: nuobackup
            configMap:
              name: {{ template "database.fullname" . }}-nuobackup
              defaultMode: 0777
          {{- if .Values.admin.tlsCACert }}
          - name: tls-ca-cert
            secret:
              secretName: {{ .Values.admin.tlsCACert.secret }}
              defaultMode: 0440
          {{- end }}
          {{- if .Values.admin.tlsClientPEM }}
          - name: tls-client-pem
            secret:
              secretName: {{ .Values.admin.tlsClientPEM.secret }}
              defaultMode: 0440
          {{- end }}
          restartPolicy: Never
{{- include "nuodb.imagePullSecrets" . | indent 10 }}
{{- end }}
{{- end }}
