{{- if .Values.database.enableDaemonSet }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.name }}-archive
  labels:
    app: nuodb
    group: nuodb
    volume: archive
spec:
  accessModes:
  {{- range .Values.database.persistence.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size | quote }}
  storageClassName: {{ .Values.database.persistence.storageClass }}
{{- if .Values.database.sm.hotCopy.enablePod }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.name }}-backup
  labels:
    app: nuodb
    group: nuodb
    volume: backup
spec:
  accessModes:
  {{- range .Values.database.sm.hotCopy.persistence.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.sm.hotCopy.persistence.size | quote }}
  storageClassName: {{ .Values.database.sm.hotCopy.persistence.storageClass }}
{{- end }}
{{- end }}
{{- if .Values.database.te.logPersistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.name }}-log-te-volume
  labels:
    app: {{ template "database.fullname" . }}
    group: nuodb
    database: {{ .Values.database.name }}
    domain: {{ .Values.admin.domain }}
    chart: {{ template "database.chart" . }}
    release: {{ .Release.Name | quote }}
spec:
  accessModes:
  {{- range .Values.database.te.logPersistence.accessModes }}
    - {{ . }}
  {{- end }}
  {{- if .Values.database.te.logPersistence.storageClass }}
  {{- if (eq "-" .Values.database.te.logPersistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.database.te.logPersistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.te.logPersistence.size }}
{{- end }}
