{{- if eq (include "defaultfalse" .Values.database.te.logPersistence.enabled) "true" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "database.fullname" . }}-log-te-volume
  labels:
    {{- include "database.resourceLabels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.database.te.logPersistence.accessModes }}
    - {{ . }}
  {{- end }}
  {{- if .Values.database.te.logPersistence.storageClass }}
  {{- if (eq "-" .Values.database.te.logPersistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.database.te.logPersistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.te.logPersistence.size }}
{{- end }}
