{{- if eq (include "defaulttrue" .Values.database.primaryRelease) "true" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "database.resourceLabels" . | nindent 4 }}
  name: {{ template "database.secretName" . }}
stringData:
  "database-name": {{ .Values.database.name | quote }}
  "database-username": {{ .Values.database.rootUser | quote }}
  "database-password": {{ .Values.database.rootPassword | quote }}
  "database-import-credentials": {{ .Values.database.autoImport.credentials | quote }}
  "database-restore-credentials": {{ .Values.database.autoRestore.credentials | quote }}
  "database-backup-credentials": {{ .Values.database.sm.hotCopy.coldStorage.credentials | quote }}
{{- end }}
