apiVersion: v1
kind: Secret
metadata:
{{- if .Values.openshift.enabled }}
  annotations:
    "template.openshift.io/expose-database-name": {{ .Values.database.name | quote }}
    "template.openshift.io/expose-username": {{ .Values.database.rootUser | quote }}
    "template.openshift.io/expose-password": {{ .Values.database.rootPassword | quote}}
{{- end }}
  labels:
    app: nuodb
    group: nuodb
    database: {{ .Values.database.name }}
    domain: {{ .Values.admin.domain }}  
  name: {{ .Values.database.name }}.nuodb.com
stringData:
  "database-name": {{ .Values.database.name | quote }}
  "database-username": {{ .Values.database.rootUser | quote }}
  "database-password": {{ .Values.database.rootPassword | quote }}
  "database-import-credentials": {{ .Values.database.import.credentials | quote }}
  "database-backup-credentials": {{ .Values.database.sm.hotCopy.coldStorage.credentials | quote }}
