{{- if eq (include "defaulttrue" .Values.database.primaryRelease) "true" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "database.resourceLabels" . | nindent 4 }}
  name: {{ template "database.secretName" . }}
stringData:
  "database-name": {{ ( include "database.dbName" . ) | quote }}
  "database-username": {{ ( include "database.rootUser" . ) | quote }}
  "database-password": {{ ( include "database.rootPassword" . )| quote }}
  "database-import-credentials": {{ .Values.database.autoImport.credentials | quote }}
  "database-restore-credentials": {{ .Values.database.autoRestore.credentials | quote }}
  "database-backup-credentials": {{ .Values.database.sm.hotCopy.coldStorage.credentials | quote }}
  "database-hostname": {{ ( include "admin.clusterip" . ) | quote }}
{{- end }}
