{{- if or (not (hasKey .Values.database.te.dbServices "enabled")) (eq (include "defaultfalse" .Values.database.te.dbServices.enabled) "true") }}
{{- if or (not (hasKey .Values.database.namespaceCoexistence "enabled")) (eq (include "defaultfalse" .Values.database.namespaceCoexistence.enabled) "false") }}
{{- if eq (include "defaulttrue" .Values.database.primaryRelease) "true" }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: |
      Cluster IP service permitting us to load balance within the cluster.
  labels:
    {{- include "database.resourceLabels" . | nindent 4 }}
  name: {{ .Values.database.name }}-{{ default .Values.admin.serviceSuffix.clusterip .Values.database.serviceSuffix.clusterip }}
spec:
  ports:
  - { name: 48006-tcp,  port: 48006,  protocol: TCP,  targetPort: 48006 }
  selector:
    domain: {{ .Values.admin.domain }}
    database: {{ .Values.database.name }}
    component: te
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: |
      Cluster IP service targeting specific Helm release permitting us to load balance within the cluster.
  labels:
    {{- include "database.resourceLabels" . | nindent 4 }}
  name: {{ template "database.fullname" . }}-{{ default .Values.admin.serviceSuffix.clusterip .Values.database.serviceSuffix.clusterip }}
spec:
  ports:
  - { name: 48006-tcp,  port: 48006,  protocol: TCP,  targetPort: 48006 }
  selector:
    app: {{ template "database.fullname" . }}
    component: te
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}
