{{- if or (not (hasKey .Values.database.te.dbServices "enabled")) ( .Values.database.te.dbServices.enabled ) }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: |
      Headless service permitting us to retrieve DNS A records that point directly to the pods backing the service.
  labels:
    app: {{ template "database.fullname" . }}
    group: nuodb
    database: {{ .Values.database.name }}
    domain: {{ .Values.admin.domain }}
    chart: {{ template "database.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ .Values.database.name }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - { name: 48006-tcp,  port: 48006,  protocol: TCP,  targetPort: 48006 }
  selector:
    app: {{ template "database.fullname" . }}
    component: te
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end}}
