apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "database.fullname" . }}
    group: nuodb
    database: {{ .Values.database.name }}
    domain: {{ .Values.admin.domain }}
    chart: {{ template "database.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ .Values.database.name }}
spec:
  clusterIP: None
  ports:
  - { name: 48006-tcp,  port: 48006,  protocol: TCP,  targetPort: 48006 }
  selector:
    app: {{ template "database.fullname" . }}
    component: te