{{- if eq (include "defaultfalse" .Values.database.legacy.headlessService.enabled) "true" }}
{{- if or (not (hasKey .Values.database.te.dbServices "enabled")) (eq (include "defaultfalse" .Values.database.te.dbServices.enabled) "true") }}
{{- if eq (include "defaulttrue" .Values.database.primaryRelease) "true" }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: |
      Headless service permitting us to retrieve DNS A records that point directly to the pods backing the service.
  labels:
    {{- include "database.resourceLabels" . | nindent 4 }}
  name: {{ include "database.dbName" . }}
spec:
  clusterIP: None
  ports:
  - { name: 48006-tcp,  port: 48006,  protocol: TCP,  targetPort: 48006 }
  selector:
    domain: {{ include "admin.domainName" . }}
    database: {{ include "database.dbName" . }}
    component: te
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}
{{- end }}
{{- end }}