## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

cloud:
  # supported: amazon, azure, google
  provider:
  # zones:
  #   - us-east-2a
  #   - us-east-2b
  #   - us-east-2c

  cluster:
    # cluster name is used to make resources unique in multi-cluster configurations.
    # If the NuoDB domain spans 2 or more physical clusters, then each cluster must have a unique cluster.name.
    # The default is fine for single-cluster domains.
    name: cluster0
    entrypointName: cluster0

admin:
  # domain is the name of the NuoDB administration domain (e.g. the cluster name)
  domain: nuodb
    
  # namespace: nuodb
  # tlsCACert:
  #   secret: nuodb-ca-cert
  #   key: ca.cert
  # tlsKeyStore:
  #   secret: nuodb-keystore
  #   key: nuoadmin.p12
  #   password: changeIt
  # tlsClientPEM:
  #   secret: nuodb-client-pem
  #   key: nuocmd.pem

backupmgr:
  enabled: true
  type: s3
  image:
    registry: 697369079385.dkr.ecr.us-east-2.amazonaws.com
    repository: nuodb/aws-sidecar
    tag: 0.2.5
    pullPolicy: Always
  init:
    enabled: false
    backup-type: backupset
    bucket: nuodb-cloud-east-2
    key: transfer/20220209T223502.tgz
    directory: init-archive