apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: {{ template "ycsb.fullname" . }}
    group: nuodb
    chart: {{ template "ycsb.chart" . }}
    release: {{ .Release.Name | quote }}
  name: {{ .Values.ycsb.loadName }}
spec:
  replicas: {{ .Values.ycsb.replicas }}
  selector:
    app: ycsb-load
  template:
    metadata:
      name: ycsb-load
      labels:
        app: ycsb-load
        database: {{ .Values.database.name }}
    spec:
      {{- with .Values.ycsb.nodeSelector }}
      nodeSelector:
{{ toYaml . | trim | indent 8 }}
      {{- end }}
{{- if .Values.ycsb.affinity }}
      affinity:
{{ tpl .Values.ycsb.affinity . | trim | indent 8 }}
{{- end }}
      {{- if .Values.ycsb.tolerations }}
      tolerations:
{{ toYaml .Values.ycsb.tolerations | trim | indent 8 }}
      {{- end }}
      containers:
      - name: ycsb-load
        image: {{ template "ycsb.image" . }}
        imagePullPolicy: {{ .Values.ycsb.image.pullPolicy }}
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.database.name }}.nuodb.com"
              key: database-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.database.name }}.nuodb.com"
              key: database-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.database.name }}.nuodb.com"
              key: database-password
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.ycsb.teDirect }}
        - { name: PEER_ADDRESS,          value: "{{ template "database.address" . }}" }
        {{- else}}
        - { name: PEER_ADDRESS,        value: "{{ template "admin.address" . }}" }
        {{- end}}
        - { name: DB_SCHEMA,           value: {{ .Values.ycsb.dbSchema | quote }} }
        - { name: YCSB_WORKLOAD,       value: {{ .Values.ycsb.workload | quote }} }
        - { name: LB_POLICY,           value: {{ .Values.ycsb.lbPolicy | quote}} }
        - { name: NO_OF_PROCESSES,     value: {{ .Values.ycsb.noOfProcesses | quote }} }
        - { name: NO_OF_ROWS,          value: {{ .Values.ycsb.noOfRows | quote }} }
        - { name: NO_OF_ITERATIONS,    value: {{ .Values.ycsb.noOfIterations | quote }} }
        - { name: OPS_PER_ITERATION,   value: {{ .Values.ycsb.opsPerIteration | quote }} }
        - { name: MAX_DELAY,           value: {{ .Values.ycsb.maxDelay | quote }} }
        - { name: TE_DIRECT,           value: {{ default false .Values.ycsb.teDirect | quote }} }
        volumeMounts:
        - name: ycsb-gen
          mountPath: /driver/ycsb_gen.sh
          subPath: ycsb_gen.sh
        - name: startup
          mountPath: /driver/startup.sh
          subPath: startup.sh
        - name: create
          mountPath: /driver/create_usertable.sh
          subPath: create_usertable.sh
{{- include "ycsb.imagePullSecrets" . | indent 6 }}
      volumes:
        - name: ycsb-gen
          configMap:
            name: {{ template "ycsb.fullname" . }}-ycsb-gen
            defaultMode: 0777
        - name: startup
          configMap:
            name: {{ template "ycsb.fullname" . }}-startup
            defaultMode: 0777
        - name: create
          configMap:
            name: {{ template "ycsb.fullname" . }}-create
            defaultMode: 0777